CREATE TABLE ip_addresses (
    id INTEGER PRIMARY KEY,
    ip1 INTEGER NOT NULL,
    ip2 INTEGER NOT NULL,
    ip3 INTEGER NOT NULL,
    ip4 INTEGER NOT NULL,
    mask1 INTEGER NOT NULL,
    mask2 INTEGER NOT NULL,
    mask3 INTEGER NOT NULL,
    mask4 INTEGER NOT NULL
);